CREATE TABLE IF NOT EXISTS "organization_position" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organization_position_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" uuid NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "organization_department" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organization_department_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" uuid NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "organization_position" ADD CONSTRAINT "organization_position_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "organization_department" ADD CONSTRAINT "organization_department_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "organization_position_org_name_unique" ON "organization_position" USING btree ("organization_id", lower(trim("name")));
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "organization_department_org_name_unique" ON "organization_department" USING btree ("organization_id", lower(trim("name")));
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_organization_position_organization_id" ON "organization_position" USING btree ("organization_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_organization_department_organization_id" ON "organization_department" USING btree ("organization_id");
--> statement-breakpoint
ALTER TABLE "organizationmember" ADD COLUMN IF NOT EXISTS "position_id" bigint;
--> statement-breakpoint
ALTER TABLE "organizationmember" ADD COLUMN IF NOT EXISTS "department_id" bigint;
--> statement-breakpoint
INSERT INTO "organization_position" ("organization_id", "name")
SELECT DISTINCT ON (m."organization_id", lower(trim(m."job_title")))
  m."organization_id", trim(m."job_title")
FROM "organizationmember" m
WHERE m."job_title" IS NOT NULL AND trim(m."job_title") <> ''
ORDER BY m."organization_id", lower(trim(m."job_title"))
ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "organization_department" ("organization_id", "name")
SELECT DISTINCT ON (m."organization_id", lower(trim(m."department")))
  m."organization_id", trim(m."department")
FROM "organizationmember" m
WHERE m."department" IS NOT NULL AND trim(m."department") <> ''
ORDER BY m."organization_id", lower(trim(m."department"))
ON CONFLICT DO NOTHING;
--> statement-breakpoint
UPDATE "organizationmember" m
SET "position_id" = p."id"
FROM "organization_position" p
WHERE m."organization_id" = p."organization_id"
  AND m."job_title" IS NOT NULL
  AND lower(trim(m."job_title")) = lower(trim(p."name"));
--> statement-breakpoint
UPDATE "organizationmember" m
SET "department_id" = d."id"
FROM "organization_department" d
WHERE m."organization_id" = d."organization_id"
  AND m."department" IS NOT NULL
  AND lower(trim(m."department")) = lower(trim(d."name"));
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "organizationmember" ADD CONSTRAINT "organizationmember_position_id_fkey" FOREIGN KEY ("position_id") REFERENCES "public"."organization_position"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "organizationmember" ADD CONSTRAINT "organizationmember_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "public"."organization_department"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_organizationmember_position_id" ON "organizationmember" USING btree ("position_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_organizationmember_department_id" ON "organizationmember" USING btree ("department_id");
--> statement-breakpoint
ALTER TABLE "organizationmember" DROP COLUMN IF EXISTS "job_title";
--> statement-breakpoint
ALTER TABLE "organizationmember" DROP COLUMN IF EXISTS "department";
