export const NAV_IDS = {
  LESSONS: 'LESSONS',
  SUBMISSIONS: 'SUBMISSIONS',
  MARKS: 'MARKS',
  CERTIFICATES: 'CERTIFICATES',
  PEOPLE: 'PEOPLE',
  SETTINGS: 'SETTINGS',
  SECTION: 'SECTION'
};

export const COURSE_SIDEBAR_DEFAULT_WIDTH = 320;
export const COURSE_SIDEBAR_MIN_WIDTH = 280;
export const COURSE_SIDEBAR_MAX_WIDTH = 420;
export const COURSE_SIDEBAR_STORAGE_KEY = 'classroomio-course-sidebar-width';
