export { default as Preview } from './certificate-preview.svelte';
export {
  ACCENT_COLORS,
  CERTIFICATE_FONT_FAMILIES,
  CERTIFICATE_LAYOUT_VERSION,
  CERTIFICATE_PAGE_HEIGHT,
  CERTIFICATE_PAGE_WIDTH,
  CERTIFICATE_PREVIEW_CONTEXT,
  CERTIFICATE_TEMPLATE_IDS,
  CERTIFICATE_TEMPLATES,
  CERTIFICATE_VARIABLES,
  createCertificateLayoutPreset,
  DEFAULT_ACCENT_COLOR,
  DEFAULT_CERTIFICATE_DESIGN,
  DEFAULT_CERTIFICATE_LAYOUT,
  isCertificateLayout,
  isCertificateVariable,
  LEGACY_THEME_MAP,
  migrateLegacyCertificateDesign,
  renderCertificate,
  renderCertificateDocument,
  resolveCertificateVariable,
  resolveTemplateId,
  splitCertificateRecipientName,
  toCertificateVariableContext,
  type AccentColor,
  type CertificateDesign,
  type CertificateFontFamily,
  type CertificateImageElement,
  type CertificateLayout,
  type CertificateLayoutElement,
  type CertificateRenderData,
  type CertificateRenderableDesign,
  type CertificateRenderResult,
  type CertificateSignatory,
  type CertificateTemplateId,
  type CertificateTemplateMeta,
  type CertificateTextElement,
  type CertificateTextStyle,
  type CertificateVariable,
  type CertificateVariableContext,
  type CertificateVariableElement
} from '@cio/certificates';
